[package]
edition.workspace = true
license.workspace = true
name = "codex-clearloop-core"
version.workspace = true

[lib]
doctest = false
name = "codex_clearloop_core"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
